### ISSUE TITLE
Move Archive-access server to Archive node runtime

### ISSUE THREAD

**Issue by koko1123** [onflow/flow-archive#103]
## Problem
the Archive-access server implements its own runtime of the Archive node's `invoker` module with the Archive node as the `index`. This makes the process inefficient as every register fetch has to be encoded and decoded between the runtimes as gRPC responses. since the server is typically run on the same machine as the Archive node, this is unnecessary.

## Solution 
Move Archive-access server to the Archive node runtime, so it can use the invoker and database as the `index` directly.

## Testing
The Archive-access server image no longer has to be deployed for the Archive node instance to run Access API

**Comment by SaveTheRbtz** [comment]
It looks like the current separation works fine for the more corse-grained APIs.

Let me try prototyping proxying the `ExecuteScript*` methods to the indexer to see how it would look.
