### ISSUE TITLE
Created automated Deployment process for DPS-live in mainnet, testnet, and canarynet

### ISSUE THREAD

**Issue by koko1123** [onflow/flow-archive#29]
## Problem
Deployment steps for `dps-live` are still manual, and since the command and system setup is all the same and parameters readily available for each spork, this can be automated

## Solution
Use the [manual deploy guide](https://www.notion.so/DPS-Deployment-Steps-116563c1c5934d90a28f2efcfdcf4fc5) as a reference and automate:
1. setup of the filesystem, perticualrly downloading the correct files to  the `/var/flow/bootstrap` directory
2. running of the command with new parameters for each spork.

**Comment by sjonpaulbrown** [comment]
This has been addressed in the [following PR](https://github.com/dapperlabs/dapper-flow-hosting/pull/834)
